# Generated by Django 3.2.7 on 2021-09-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Edizm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='ЕдИзм')),
            ],
            options={
                'verbose_name': 'ЕдИзм',
                'verbose_name_plural': 'ЕдИзм',
            },
        ),
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинет',
            },
        ),
        migrations.CreateModel(
            name='NamKabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=100, verbose_name='Название кабинета')),
            ],
            options={
                'verbose_name': 'Название кабинета',
                'verbose_name_plural': 'Название кабинета',
            },
        ),
        migrations.CreateModel(
            name='NalichiTehniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodTMU', models.IntegerField(default=11111111, verbose_name='КодТМУ')),
                ('Naimenovanie', models.CharField(max_length=255, null=True, verbose_name='Наименования')),
                ('Kolich', models.IntegerField(default=1, verbose_name='Количество')),
                ('sostoyanie', models.CharField(choices=[('рабочий', 'рабочий'), ('не рабочий', 'не рабочий')], max_length=20, null=True, verbose_name='Состояние')),
                ('Edizm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Факультет.edizm', verbose_name='Ед.изм.')),
                ('Kabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Факультет.kabinet', verbose_name='Кабинет')),
                ('NamKabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Факультет.namkabinet', verbose_name='Тип Кабинета')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Факультет.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Наличие техники',
                'verbose_name_plural': 'Наличие техники',
            },
        ),
        migrations.AddField(
            model_name='kabinet',
            name='NamKabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Факультет.namkabinet', verbose_name='Название кабинета'),
        ),
    ]
