# Generated by Django 3.2.7 on 2021-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Факультет', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalichitehniki',
            name='kodTMU',
            field=models.IntegerField(verbose_name='КодТМУ'),
        ),
    ]
