# Generated by Django 3.2.7 on 2021-09-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Факультет', '0002_alter_nalichitehniki_kodtmu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naimenovanie', models.CharField(max_length=50, verbose_name='Учебный корпус')),
            ],
            options={
                'verbose_name': 'Учебный корпус',
                'verbose_name_plural': 'Учебный корпус',
            },
        ),
        migrations.AddField(
            model_name='nalichitehniki',
            name='Corps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Факультет.corps', verbose_name='Учебный корпус'),
            preserve_default=False,
        ),
    ]
